/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 --transform combination-padlock.glb
*/

import React, { forwardRef, useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Model = forwardRef(function(props: any, ref) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/res/combination-padlock-transformed.glb')
  return (
    <group {...props} dispose={null} ref={ref}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.nOmba2} skeleton={nodes.Object_7.skeleton} position={[0, -0.422, 0]} />
    </group>
  )
})

useGLTF.preload('/res/combination-padlock-transformed.glb')
