/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 crowbar.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props: any) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/res/crowbar-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.crowbar_01.geometry} material={materials.crowbar_01} />
    </group>
  )
}

useGLTF.preload('/res/crowbar-transformed.glb')
