/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 picture.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props: any) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/res/picture-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fancy_picture_frame_01.geometry} material={materials.fancy_picture_frame_01} />
      <mesh geometry={nodes.fancy_picture_frame_01_canvas.geometry} material={materials.fancy_picture_frame_01_canvas} />
    </group>
  )
}

useGLTF.preload('/res/picture-transformed.glb')
